**Numpy :**

In [2]:
import numpy as np

In [3]:
import sys

In [3]:
# Create a list of 1000000 integers
list_1000000 = list(range(1000000))

# Create a NumPy array of 1000000 integers
array_1000000 = np.arange(1000000)

# Print the size of the list and the array in bytes
print(f"Size of list: {sys.getsizeof(list_1000000)} bytes")
print(f"Size of array: {array_1000000.nbytes} bytes")

# Time how long it takes to sum the list and the array

import time

# Sum the list
start_time = time.time()
sum_list = sum(list_1000000)
end_time = time.time()
list_sum_time = (end_time - start_time) * 1000

# Sum the array
start_time = time.time()
sum_array = np.sum(array_1000000)
end_time = time.time()
array_sum_time = (end_time - start_time) * 1000

# Print the time it took to sum the list and the array
print(f"Time to sum list: {list_sum_time:.2f} milliseconds")
print(f"Time to sum array: {array_sum_time:.2f} milliseconds")

Size of list: 8000056 bytes
Size of array: 8000000 bytes
Time to sum list: 7.64 milliseconds
Time to sum array: 1.07 milliseconds


### NumPy Arrays

np.arange():

np.arange() is a function in NumPy used to create an array with regularly spaced values within a specified range.

Its syntax is: numpy.arange([start, ]stop, [step, ]dtype=None)

In [5]:
arr = np.arange(10)
print(arr,type(arr),arr.size, arr.ndim, arr.shape, sep='\n')

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
10
1
(10,)


In [18]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d, type(arr_1d), arr_1d.ndim, arr_1d.size, arr_1d.shape, arr_1d.dtype, sep='\n')
print(arr_1d[0]) # index

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
5
(5,)
int64
1


In [19]:
# Create a 2D array
arr_2d = np.array([
                   [1, 2, 3],
                   [4, 5, 6]
                  ])
print(arr_2d, type(arr_2d),arr_2d.ndim, arr_2d.size, arr_2d.shape, arr_2d.dtype, sep='\n')

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
6
(2, 3)
int64


In [22]:
# Create a 3D array
arr_3d = np.zeros((2, 3, 4))
print(arr_3d, arr_3d.ndim, arr_3d.size, arr_3d.shape, sep='\n')


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3
24
(2, 3, 4)


In [24]:
# Create a 4D array
arr_4d = np.ones((2, 3, 4, 5))
print(arr_4d)

# Print the number of dimensions
print("Number of dimensions:", arr_4d.ndim)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
Number of dimensions: 4


### Properties of nd Arrays

* type(arr)
* size
* shape
* ndim
* dtype (int64)


In [21]:
# Create an array with a specific data type
arr_float = np.array([1.1, 2.2, 3.3]) # ,dtype=np.float32
# Print the data type
print("Data type of the array:", arr_float.dtype)

Data type of the array: float64


### The itemsize attribute of an ndarray specifies the size of each element in bytes.

In [25]:
# Create an array of integers
arr_int = np.array([1, 2, 3])
print(arr_int.dtype)
# Print the item size
print("Size of each element (in bytes):", arr_int.itemsize)

int64
Size of each element (in bytes): 8


**NumPy Data Types (dtypes):**

NumPy provides a variety of data types to represent different kinds of numerical data. These data types are important for controlling memory usage and ensuring data integrity in numerical computations.

**Common NumPy Data Types:**

- **int**: Integer (default size depends on the platform).
- **float**: Floating point number (default size depends on the platform).
- **bool**: Boolean (True or False).
- **complex**: Complex number with real and imaginary parts.
- **uint**: Unsigned integer (no negative values).

**Specifying Data Types:**

You can specify the data type of an ndarray using the `dtype` parameter of NumPy functions or by providing the data type as an argument to the array creation functions.

In [28]:
# Create an array with a specific data type
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_float64 = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print(arr_int32,arr_int32.dtype)
print(arr_float64,arr_float64.dtype)

[1 2 3] int32
[1.1 2.2 3.3] float64


**Precision:**

Precision refers to the level of detail and accuracy with which numerical values are represented. NumPy data types have different levels of precision, which determine the range of values they can represent and the amount of memory they occupy.

In [32]:
# Create an array with different data types
arr_int32 = np.array([1234567890, 1234567890], dtype=np.int32)
arr_int64 = np.array([1234567890, 1234567890], dtype=np.int64)

print("Data type of arr_int32:", arr_int32.dtype)
print("Data type of arr_int64:", arr_int64.dtype)

print(arr_int32)

#In this example, the `int32` data type has limited precision compared to `int64`,
# which can represent larger integers without loss of precision.


Data type of arr_int32: int32
Data type of arr_int64: int64
[1234567890 1234567890]


### Impact of Precision on Memory Usage:

In [33]:
# Create arrays with different data types
arr_float32 = np.array([1.1, 2.2, 3.3], dtype=np.float32)
arr_float64 = np.array([1.1, 2.2, 3.3], dtype=np.float64)

print("Memory usage of arr_float32:", arr_float32.itemsize * arr_float32.size, "bytes")  # Output: 12 bytes (3 elements * 4 bytes/element)
print("Memory usage of arr_float64:", arr_float64.itemsize * arr_float64.size, "bytes")  # Output: 24 bytes (3 elements * 8 bytes/element)

Memory usage of arr_float32: 12 bytes
Memory usage of arr_float64: 24 bytes


### Example differentiating float32 and float64:

In [34]:
# Create a large array with float32 and float64 data types
large_array_float32 = np.arange(1000000, dtype=np.float32)
large_array_float64 = np.arange(1000000, dtype=np.float64)

# Calculate the sum of elements
sum_float32 = np.sum(large_array_float32)
sum_float64 = np.sum(large_array_float64)

print("Sum using float32:", sum_float32)
print("Sum using float64:", sum_float64)

Sum using float32: 499999800000.0
Sum using float64: 499999500000.0


### Example differentiating float32 and float64:

In [35]:
# Create a large array with float32 and float64 data types
large_array_float32 = np.arange(1000000, dtype=np.float32)
large_array_float64 = np.arange(1000000, dtype=np.float64)

# Calculate the sum of elements
sum_float32 = np.sum(large_array_float32)
sum_float64 = np.sum(large_array_float64)

print("Sum using float32:", sum_float32)
print("Sum using float64:", sum_float64)

Sum using float32: 499999800000.0
Sum using float64: 499999500000.0


### <b> np.zeros, np.ones, np.full:

In [36]:
# Create a 2x3 array filled with zeros
zeros_array = np.zeros((2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
# Create a 3x2 array filled with ones
ones_array = np.ones((3, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
# Create a 2x2 array filled with 5
full_array = np.full((2, 2), 5)
print(full_array)

[[5 5]
 [5 5]]


## Array Operations - NumPy

### Arithmetic

In [40]:
# Addition
arr_sum = np.add([1, 2, 3], [4, 5, 6])
print("Addition:", arr_sum)

# Subtraction
arr_diff = np.subtract([5, 6, 7], [2, 3, 1])
print("Subtraction:", arr_diff)

# Multiplication
arr_prod = np.multiply([2, 3, 4], [3, 4, 5])
print("Multiplication:", arr_prod)

# Division
arr_div = np.divide([10, 12, 14], [2, 3, 2])
print("Division:", arr_div)

# Modulus
arr_mod = np.mod([10, 11, 12], [3, 4, 5])
print("Modulus:", arr_mod)

# Exponentiation
arr_pow = np.power([2, 3, 4], [2, 3, 2])
print("Exponentiation:", arr_pow)


Addition: [5 7 9]
Subtraction: [3 3 6]
Multiplication: [ 6 12 20]
Division: [5. 4. 7.]
Modulus: [1 3 2]
Exponentiation: [ 4 27 16]


## Relational Operations:

In [41]:
# Create sample arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 2, 4, 3])

# Equal
print("Equal:", arr1 == arr2)

# Not Equal
print("Not Equal:", arr1 != arr2)

# Greater Than
print("Greater Than:", arr1 > arr2)

# Greater Than or Equal To
print("Greater Than or Equal To:", arr1 >= arr2)

# Less Than
print("Less Than:", arr1 < arr2)

# Less Than or Equal To
print("Less Than or Equal To:", arr1 <= arr2)


Equal: [False  True False False]
Not Equal: [ True False  True  True]
Greater Than: [False False False  True]
Greater Than or Equal To: [False  True False  True]
Less Than: [ True False  True False]
Less Than or Equal To: [ True  True  True False]


# Indexing and Slicing for 1D Arrays

In [42]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Access individual elements using indexing
print("First element:", arr[0])
print("Second element:", arr[1])
print("Last element:", arr[-1])

First element: 1
Second element: 2
Last element: 5


### slicing

In [44]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Slice elements from index 1 to index 3 (exclusive)
print("Slice:", arr[1:3])

# Slice elements from index 0 to index 4 with step size 2
print("Slice with step:", arr[0:4:2])

Slice: [2 3]
Slice with step: [1 3]


In [45]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Access the last element using negative indexing
print("Last element:", arr[-1])

Last element: 5


**Slicing with Omitted Indices:**

You can omit any of the slicing parameters to use default values. Omitting `start` defaults to 0, omitting `stop` defaults to the end of the array, and omitting `step` defaults to 1.

In [46]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Slice elements from the beginning to index 3 (exclusive)
print("Slice with omitted start:", arr[:3])

# Slice elements from index 2 to the end
print("Slice with omitted stop:", arr[2:])

# Slice elements with step size 2
print("Slice with omitted step:", arr[::2])

Slice with omitted start: [1 2 3]
Slice with omitted stop: [3 4 5]
Slice with omitted step: [1 3 5]


## Indexing and Slicing for 2D Arrays

In [47]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Access individual elements using indexing
print("Element at (0, 0):", arr[0, 0])
print("Element at (1, 2):", arr[1, 2])

Element at (0, 0): 1
Element at (1, 2): 6


In [48]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Slice elements from rows 0 to 1 (exclusive) and columns 1 to 2 (exclusive)
print("Slice:", arr[0:2, 1:3])


# Modify slice
arr[0:2, 1:3] = [[10, 20], [30, 40]]
print("Modified array after slicing:", arr)


Slice: [[2 3]
 [5 6]]
Modified array after slicing: [[ 1 10 20]
 [ 4 30 40]
 [ 7  8  9]]


In [49]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Access the last element using negative indexing
print("Last element:", arr[-1, -1])  # Output: 9

Last element: 9


In [50]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Slice elements from rows 1 to the end and all columns
print("Slice with omitted start and stop:", arr[1:])

# Slice elements from all rows and columns 0 to 1 (exclusive) with step size 2
print("Slice with omitted step:", arr[:, 0:2:2])

Slice with omitted start and stop: [[4 5 6]
 [7 8 9]]
Slice with omitted step: [[1]
 [4]
 [7]]


## Mass Level Indexing and Slicing

**1. Boolean Indexing:**

Boolean indexing allows you to select elements from an array based on a condition. You create a boolean mask indicating which elements satisfy the condition, and then use this mask to extract the desired elements.

In [51]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Boolean mask for elements greater than 3
mask = arr_1d > 3

# Use boolean mask to select elements
selected_elements = arr_1d[mask]
print("Selected elements:", selected_elements)

Selected elements: [4 5]


In [53]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], # False, False, True
                    [4, 5, 6],
                    [7, 8, 1]])

# Boolean indexing to select elements greater than 2
result_2d = arr_2d[arr_2d > 2]
print("Elements greater than 2 in 2D array:", result_2d)


Elements greater than 2 in 2D array: [3 4 5 6 7 8]


**2. Fancy Indexing:**

Fancy indexing allows you to select elements from an array using arrays of indices. You provide arrays of indices along each axis, and the elements at those indices are returned as a new array.

In [54]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Fancy indexing
indices = [0, 2, 4]
selected_elements = arr_1d[indices]
print("Selected elements:", selected_elements)

Selected elements: [1 3 5]


# <b> <i>Playing with Arrays

**1. Transposing Arrays:**

Transposing an array means exchanging its rows and columns. In NumPy, you can transpose an array using the `T` attribute or the `transpose()` function.

In [57]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])

print("Oroginal Array:",'\n',arr_2d)
# Transpose the array
transposed_arr = arr_2d.T
print("Transposed array:")
print(transposed_arr)

Oroginal Array: 
 [[1 2 3]
 [4 5 6]]
Transposed array:
[[1 4]
 [2 5]
 [3 6]]


**2. Swapping Axes:**

Swapping axes means rearranging the dimensions of an array. You can swap axes using the `swapaxes()` function.

In [58]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Swap axes
swapped_arr = arr_2d.swapaxes(0,1)
print("Swapped array:")
print(swapped_arr)

Swapped array:
[[1 4]
 [2 5]
 [3 6]]


In [4]:
# Create a 3D array of shape (2, 3, 4)
# Think of it as 2 layers of 3x4 matrices
array_3d = np.array([[[ 1,  2,  3,  4],
                      [ 5,  6,  7,  8],
                      [ 9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

print("Original array shape:", array_3d.shape)

# Swap the first and last axes (depth with columns)
swapped_array = np.swapaxes(array_3d, 0, 2)

print("Swapped array shape:", swapped_array.shape)
print("Swapped array data:\n", swapped_array)


Original array shape: (2, 3, 4)
Swapped array shape: (4, 3, 2)
Swapped array data:
 [[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


**3. Pseudo-random Number Generation:**

NumPy provides various functions for generating pseudo-random numbers. These functions are located in the `numpy.random` module. You can generate random numbers from different distributions, such as uniform, normal, binomial, etc.

In [5]:
# Pseudo-random Number Generation in 1D Array:

# Generate 5 random integers between 1 and 10
random_integers = np.random.randint(1, 10, size=5)
print("Random integers (1D):", random_integers)

# Generate 5 random numbers from a normal distribution
random_normal = np.random.normal(size=5)
print("Random numbers from normal distribution (1D):", random_normal)

Random integers (1D): [1 3 6 9 6]
Random numbers from normal distribution (1D): [-0.91902787 -0.84076549 -1.49820603 -0.82043204  0.75567678]


In [6]:
# Pseudo-random Number Generation in 2D Array:

# Generate a 2D array of shape (3, 3) with random integers between 1 and 10
random_integers_2d = np.random.randint(1, 10, size=(3, 3))
print("Random integers (2D):")
print(random_integers_2d)

# Generate a 2D array of shape (3, 3) with random numbers from a normal distribution
random_normal_2d = np.random.normal(size=(3, 3))
print("Random numbers from normal distribution (2D):")
print(random_normal_2d)

Random integers (2D):
[[7 4 2]
 [8 5 4]
 [6 8 8]]
Random numbers from normal distribution (2D):
[[-2.23151575  1.15755695 -1.39189029]
 [-0.59832481  0.7525723   0.66380418]
 [ 1.25987196  1.07265672 -3.19900459]]


## Masking

Masking in NumPy involves using boolean arrays (masks) to filter or select elements from arrays based on certain conditions. This is particularly useful for selecting elements that satisfy specific criteria.

In [7]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Create a boolean mask based on a condition (e.g., elements greater than 2)
mask_1d = arr_1d > 2

# Apply the mask to select elements from the array
result_1d = arr_1d[mask_1d]

print("Original 1D array:", arr_1d)
print("Boolean mask:", mask_1d)
print("Selected elements using mask:", result_1d)

Original 1D array: [1 2 3 4 5]
Boolean mask: [False False  True  True  True]
Selected elements using mask: [3 4 5]


In [8]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create a boolean mask based on a condition (e.g., elements greater than 5)
mask_2d = arr_2d > 5

# Apply the mask to select elements from the array
result_2d = arr_2d[mask_2d]

print("Original 2D array:")
print(arr_2d)

print("Boolean mask:")
print(mask_2d)

print("Selected elements using mask:")
print(result_2d)

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Boolean mask:
[[False False False]
 [False False  True]
 [ True  True  True]]
Selected elements using mask:
[6 7 8 9]


### Operations on 2D Arrays

**1. Matrix Multiplication (`np.matmul()`):**

Matrix multiplication is a fundamental operation in linear algebra, where you multiply two matrices to obtain a new matrix. In NumPy, you can perform matrix multiplication using the `np.matmul()` function.

In [9]:
# Define matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Matrix multiplication using np.matmul()
result = np.matmul(matrix_a, matrix_b)
print("Matrix Multiplication:")
print(result)

Matrix Multiplication:
[[19 22]
 [43 50]]


**2. Reshaping (`np.reshape()`):**

Reshaping an array means changing the shape of the array without changing its data. It's useful for converting arrays between different dimensions or rearranging their layout.

In [10]:
# Reshaping an array
arr = np.arange(1, 10)  # 1D array from 1 to 9
print(arr)
reshaped_arr = arr.reshape((3, 3))  # Reshape to a 3x3 matrix
print("Reshaped array:")
print(reshaped_arr)

[1 2 3 4 5 6 7 8 9]
Reshaped array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**3. Transpose (`np.transpose()`):**

Transposing a matrix means flipping its rows with its columns. In NumPy, you can obtain the transpose of a matrix using the `np.transpose()` function or the `.T` attribute.

In [11]:
# Transposing a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
transposed_matrix = np.transpose(matrix)
print("Transposed matrix:")
print(transposed_matrix)

Transposed matrix:
[[1 4]
 [2 5]
 [3 6]]


**4. Aggregate Functions:**

Aggregate functions in NumPy are functions that operate on arrays and return a single value, summarizing the data in some way. Common aggregate functions include `np.sum()`, `np.max()`, `np.min()`, `np.mean()`, etc.

In [13]:
# Aggregate functions
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Sum of all elements:", np.sum(matrix))
print("Maximum element:", np.max(matrix))
print("Minimum element:", np.min(matrix))
print("Mean of all elements:", np.mean(matrix))

Sum of all elements: 21
Maximum element: 6
Minimum element: 1
Mean of all elements: 3.5


### <b> Universal Functions (ufuncs)

**1. Basic Arithmetic Operations:**

In [14]:
# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Element-wise addition
result_add = np.add(arr, 2)  # Add 2 to each element
print("Addition:", result_add)

# Element-wise multiplication
result_mul = np.multiply(arr, 3)  # Multiply each element by 3
print("Multiplication:", result_mul)

Addition: [3 4 5 6 7]
Multiplication: [ 3  6  9 12 15]


**2. Trigonometric Functions:**

In [15]:
# Trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi])

# Sine
result_sin = np.sin(angles)
print("Sine:", result_sin)

# Cosine
result_cos = np.cos(angles)
print("Cosine:", result_cos)

Sine: [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
Cosine: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]


**3. Exponential and Logarithmic Functions:**

In [16]:
# Exponential and logarithmic functions
arr = np.array([1, 2, 3, 4, 5])

# Exponential
result_exp = np.exp(arr)
print("Exponential:", result_exp)

# Natural logarithm
result_log = np.log(arr)
print("Natural Logarithm:", result_log)

Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


**4. Statistical Functions:**

In [17]:
# Statistical functions
arr = np.array([1, 2, 3, 4, 5])

# Mean
result_mean = np.mean(arr)
print("Mean:", result_mean)

# Standard deviation
result_std = np.std(arr)
print("Standard Deviation:", result_std)

Mean: 3.0
Standard Deviation: 1.4142135623730951


**5. Comparison Functions:**

In [18]:
# Comparison functions
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 3, 4, 4])

# Greater than
result_gt = np.greater(arr1, arr2)
print("Greater Than:", result_gt)

# Less than or equal to
result_lte = np.less_equal(arr1, arr2)
print("Less Than or Equal To:", result_lte)

Greater Than: [False False False False  True]
Less Than or Equal To: [ True  True  True  True False]


**6. Broadcasting:**

Ufuncs also support broadcasting, which means they can operate on arrays of different shapes. NumPy automatically broadcasts arrays to perform element-wise operations.

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Element-wise addition with scalar
result_broadcast = arr + 2
print("Broadcasting with Scalar:")
print(result_broadcast)

Broadcasting with Scalar:
[[3 4 5]
 [6 7 8]]


## # Array Manipulations

### <b> Playing with Shapes

**1. reshape:** The reshape method returns a new array with the specified shape, without changing the data.

In [20]:
# Create a one-dimensional array of 12 elements
a = np.arange(12)
print("Original array:", a)

# Reshape it to a 3x4 two-dimensional array
b = a.reshape(3,4)
print("Reshaped array:\n", b)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**2. resize:** The resize method changes the shape and size of an array in-place. This method can alter the original array and fill in with repeated copies of a if the new array is larger than the original.

In [21]:
# Resize the array in-place to 2x6
a = np.arange(10)
a.resize(2, 6)
print("Resized array:\n", a)

Resized array:
 [[0 1 2 3 4 5]
 [6 7 8 9 0 0]]


**3. ravel:** The ravel method returns a flattened one-dimensional array. It's a convenient way to convert any multi-dimensional array into a flat 1D array.

In [22]:
# Flatten the 3x4 array to a one-dimensional array
print(b)
flat = b.ravel()
print("Flattened array:", flat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


**4. flatten:** Similar to ravel, but flatten returns a copy instead of a view of the original data, thus not affecting the original array.

In [23]:
# Create a copy of flattened array
print(b)
flat_copy = b.flatten()
print("Flattened array copy:", flat_copy)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array copy: [ 0  1  2  3  4  5  6  7  8  9 10 11]


**Difference between ravel and flatten:**

In [24]:
# Creating a 2D array
a = np.array([[1, 2], [3, 4]])

# Flattening using ravel
b = a.ravel()
b[0] = 100  # Modifying the raveled array

# Flattening using flatten
c = a.flatten()
c[1] = 200  # Modifying the flattened array

print("Original array after modifying raveled array:", a)
print("Original array after modifying flattened array does not change:", a)


Original array after modifying raveled array: [[100   2]
 [  3   4]]
Original array after modifying flattened array does not change: [[100   2]
 [  3   4]]


**5. squeeze:** The squeeze method is used to remove axes of length one from an array.

In [25]:
# Create an array with a singleton dimension
c = np.array([[[1, 2, 3, 4]]])
print("Original array with singleton dimension:", c.shape)

# Squeeze to remove singleton dimensions
squeezed = c.squeeze()
print(squeezed)
print("Squeezed array:", squeezed.shape)

Original array with singleton dimension: (1, 1, 4)
[1 2 3 4]
Squeezed array: (4,)


**6. expand_dims:** The opposite of squeeze, expand_dims is used to add an axis at a specified position.

In [26]:
# Add an axis at index 1
expanded = np.expand_dims(squeezed, axis=1)
print(expanded)
print("Expanded array shape:", expanded.shape)

[[1]
 [2]
 [3]
 [4]]
Expanded array shape: (4, 1)


# Splitting and Joining
Splitting allows you to divide large arrays into smaller arrays. This can be useful for parallel processing tasks or during situations where subsets of data need to be analyzed separately.

**1. np.split:** Splits an array into multiple sub-arrays.

In [27]:
x = np.arange(9)
print("Original array:", x)

# Split the array into 3 equal parts
x_split = np.split(x, 3)
print("Split array:", x_split)

Original array: [0 1 2 3 4 5 6 7 8]
Split array: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


**2. np.array_split:** Similar to np.split, but allows for splitting into unequal subarrays.

In [28]:
# Split the array into 4 parts, which will not be equal
x_array_split = np.array_split(x, 4)
print("Array split into unequal parts:", x_array_split)

Array split into unequal parts: [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


**3. np.hsplit and np.vsplit:** These are specific cases of split for horizontal and vertical splitting respectively, useful for 2D arrays (matrices).

In [29]:
y = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D array:\n", y)

# Horizontal split
y_hsplit = np.hsplit(y, 3)
print("Horizontally split:", y_hsplit)

# Vertical split
y_vsplit = np.vsplit(y, 2)
print("Vertically split:", y_vsplit)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Horizontally split: [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
Vertically split: [array([[1, 2, 3]]), array([[4, 5, 6]])]


**4. np.concatenate:** Concatenates a sequence of arrays along an existing axis.

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate along the first axis
concatenated = np.concatenate((a, b))
print("Concatenated array:", concatenated)

Concatenated array: [1 2 3 4 5 6]


**5. np.hstack and np.vstack:** These are specific cases of concatenate for horizontal and vertical stacking respectively.

In [31]:
# Horizontal stack
h_stacked = np.hstack((a, b))
print("Horizontally stacked:", h_stacked)

# Vertical stack
v_stacked = np.vstack((a, b))
print("Vertically stacked:\n", v_stacked)

Horizontally stacked: [1 2 3 4 5 6]
Vertically stacked:
 [[1 2 3]
 [4 5 6]]


# Adding and Removing Elements
These operations allow you to modify array sizes dynamically.

**1. np.append:** Adds elements to the end of an array.

In [32]:
# Append elements to the array
a = np.array([1, 2, 3])
appended = np.append(a, [7, 8])
print("Appended array:", appended)

Appended array: [1 2 3 7 8]


**2. np.insert:** Inserts elements at a specific position in the array.

In [33]:
# Insert elements into the array
inserted = np.insert(a, 1, [9, 10])
print("Array with inserted elements:", inserted)

Array with inserted elements: [ 1  9 10  2  3]


**3. np.delete:** Removes elements at a specific position from the array.

In [34]:
# Create a one-dimensional array
a = np.array([1, 2, 3, 4, 5])

# Delete the element at index 2
result = np.delete(a, 2)
print("Array after deleting element at index 2:", result)

Array after deleting element at index 2: [1 2 4 5]


In [35]:
# Delete multiple elements
result = np.delete(a, [0, 3])
print("Array after deleting elements at indices 0 and 3:", result)

Array after deleting elements at indices 0 and 3: [2 3 5]


In [36]:
# Create a two-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Delete the second row
result = np.delete(b, 1, axis=0)
print("Array after deleting second row:\n", result)

# Delete the third column
result = np.delete(b, 2, axis=1)
print("Array after deleting third column:\n", result)

Array after deleting second row:
 [[1 2 3]
 [7 8 9]]
Array after deleting third column:
 [[1 2]
 [4 5]
 [7 8]]
